name: NodeJS with Webpack

on:
  push:
    branches: [main]

jobs:
  production-deloy:
    if: |
      !contains(github.event.head_commit.message, 'Build action:')
      && github.event.head_commit.author.name != 'shopify[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install
        run: npm ci

      - name: Build
        run: npx webpack

      - name: Push
        uses: avex-designs/shopify-webpack-build-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
          BRANCH: main
          FOLDERS: assets,snippets
          MESSAGE: "Build action: ({sha}) {msg}"

          # if: "!contains(github.event.head_commit.message, 'SKIP SCRIPTS')"
